application:
  subdomain: con-nav-item
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://con-nav-item:3000/

  injects:
    - id: admin-login-autofill
      when:
        - /admin
      do:
        - src: builtin://simple-inject-password
          params:
            user: "{{ .U.admin_username }}"
            password: "{{ .U.admin_password }}"

services:
  con-nav-item:
    # ghcr.io/zczy-k/smartnavora:latest
    image: registry.lazycat.cloud/czyt/zczy-k/con-nav-item:a0d4c3d2bfa55c5a
    binds:
      - /lzcapp/var/data:/app/database
      - /lzcapp/var/backups:/app/backups
      - /lzcapp/var/config:/app/config

    environment:
      - PORT=3000 # 监听端口
      - NODE_ENV=production # 运行环境
      - ADMIN_USERNAME={{.U.admin_username}} # 后台用户名
      - ADMIN_PASSWORD={{.U.admin_password}} # 后台密码
      - JWT_SECRET={{ stable_secret "jwt#secret" }} # JWT密钥（必须修改！）
      - CRYPTO_SECRET={{ stable_secret "crypto_secret" }}
      - AUTO_BACKUP_ENABLED=true
