application:
  subdomain: con-nav-item
  background_task: true
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://con-nav-item:3000/
  injects:
    - id: admin-login-autofill
      when:
        - /admin
      do:
        - src: builtin://simple-inject-password
          params:
            user: "{{ .U.admin_username }}"
            password: "{{ .U.admin_password }}"
services:
  con-nav-item:
    # ghcr.io/zczy-k/smartnavora:latest
    # upstream: ghcr.io/zczy-k/smartnavora:latest@sha256:483c656100e8daf1cacdba4fd94b670415b247c1ddd4e4551095ccc726947d3d
    image: registry.lazycat.cloud/czyt/zczy-k/smartnavora:4a2f09ad8dd1b3c4
    binds:
      - /lzcapp/var/data:/app/database
      - /lzcapp/var/backups:/app/backups
      - /lzcapp/var/config:/app/config
    environment:
      - PORT=3000 # 监听端口
      - NODE_ENV=production # 运行环境
      - ADMIN_USERNAME={{.U.admin_username}} # 后台用户名
      - ADMIN_PASSWORD={{.U.admin_password}} # 后台密码
      - JWT_SECRET={{ stable_secret "jwt#secret" }} # JWT密钥（必须修改！）
      - CRYPTO_SECRET={{ stable_secret "crypto_secret" }}
      - AUTO_BACKUP_ENABLED=true
